---
title: 'The Beer Necessities'
author: "Team: Carly Seeck, Drew Hirsh,  Eric Hedgren, Henry Eichten, Gavin Fisher"
date: "11/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For data exploration, our data sets are relatively clean so little will need to be done for manipulation. Below are the questions divided between our group for the project.

Questions by member:

Carly:
How does the Alcohol content of the beer affect its overall rating?
Can we predict the rating of a beer based on its characteristics?

Drew:
Which Brewery has the highest rated beers?
How does the IBU score affect the overall score?

Eric:
Which beers have the highest aroma, appearance, palate, and taste ratings?
What are the most common characteristics of beer?

Henry:
Which combination of mouth feel, taste, and flavor/aroma characteristics returns the highest ratings?
Can we find what characteristics will likely cause a beer to be rated highly?

Gavin:
What are the most popular beer styles?
Can we recommend other beers if someone picks a beer they like?



