---
title: 'The Beer Necessities'
author: "Team: Carly Seeck, Drew Hirsh,  Eric Hedgren, Henry Eichten, Gavin Fisher"
date: "11/27/2023"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(readxl)
library(viridis)
library(tidyr)
library(dplyr)

limit <- 100
```

Importing the Dataset.
```{r}
data <- read.csv("./beer_profile_and_ratings.csv")
head(data, 3)
```

Which combination of mouth feel, taste, and flavor/aroma characteristics returns the highest ratings?

```{r}
percents_flavor_data <- data.frame(data["review_overall"])

percents_flavor_data$'%Bitter' <- round(data$Bitter / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Sweet' <- round(data$Sweet / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Sour' <- round(data$Sour / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Salty' <- round(data$Salty / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Fruits' <- round(data$Fruits / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Hoppy' <- round(data$Hoppy / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Spices' <- round(data$Spices / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

percents_flavor_data$'%Malty' <- round(data$Malty / rowSums(data[, c("Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty")]), 5)

limited_percents_flavor_data <- top_n(percents_flavor_data, limit, review_overall)

head(percents_flavor_data)
```

```{r}
flavor_data <- data[order(-data$review_overall), ]
flavor_data <- flavor_data[c("review_overall", "Bitter", "Sweet", "Sour", "Salty", "Fruits", "Hoppy", "Spices", "Malty" )]

limited_flavor_data <- top_n(flavor_data, limit, review_overall)

top_10 <- top_n(flavor_data, 10, review_overall)

print(top_10)
```

Data visualized by percent of variable of sum of all variables by raw values.
```{r}
limited_percents_flavor_data <- limited_percents_flavor_data[order(limited_percents_flavor_data$review_overall), ]

limited_percents_flavor_data %>%
    tidyr::gather(variable, value, -review_overall) %>%
    ggplot(aes(x = variable, y = value, fill = variable)) +
        geom_boxplot() +
        theme_minimal()
```

Data visualized by raw values.
```{r}
limited_flavor_data <- limited_flavor_data[order(limited_flavor_data$review_overall), ]

limited_flavor_data %>%
    tidyr::gather(variable, value, -review_overall) %>%
    ggplot(aes(x = variable, y = value, fill = variable)) +
        geom_boxplot() +
        theme_minimal()
```

Can we find what characteristics will likely cause a beer to be rated highly?
